project:
  type: website

website:
  title: "neural-diffeqs"
  favicon:
  image: ../assets/neural_diffeqs.logo.[mg
  navbar: ../assets/neural_diffeqs.favicon.png
    logo:
    tools:
      - icon: twitter
        href: https://twitter.com/vinyard_m
      - icon: github
        href: https://github.com/mvinyard/neural-diffeqs
        menu:
          - text: Source Code
            url:  https://github.com/neural-diffeqs/neural-diffeqs/
          - text: Open an issue
            url:  https://github.com/neural-diffeqs/neural-diffeqs/issues/new

  sidebar:
    contents:
      - text: Home
        href: index.qmd
      - text: Quickstart
        href: quickstart.qmd
      - text: Installation
        href: install.qmd
      - section: "API reference"
        href: api.qmd          
        contents:
          - text: NeuralSDE
            href: neural_sde.qmd
          - text: NeuralODE
            href: neural_sde.qmd
          - text: Neural Differential Equations with a prior
            href: neural_sde.qmd
      
      - section: "Gallery of examples"
        href: examples.qmd
      - section: "About"
        href: about.qmd
        contents:
          - text: Development team
            href: team.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

output:
  html_document:
    css: "styles.css"
